## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()
unique_values

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_type_counts[application_type_counts < 1500].index)

# Replace in dataframe
application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].apply(lambda x: 'Other' if x in application_types_to_replace else x)

for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
Other     5720
T4        1542
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_type_counts = application_df["CLASSIFICATION"].value_counts()
classification_type_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_type_counts[classification_type_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() < 1500].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_encoded_df = pd.get_dummies(application_df)
application_encoded_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,1,0,0,0,1,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,1,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,1,0,0,0,1,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_encoded_df.drop('IS_SUCCESSFUL', axis=1)
y = application_encoded_df['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=150, input_dim=len(X_train.columns))) 
nn.add(tf.keras.layers.BatchNormalization())
nn.add(tf.keras.layers.Activation('relu'))
nn.add(tf.keras.layers.Dropout(0.4))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=75))
nn.add(tf.keras.layers.BatchNormalization())
nn.add(tf.keras.layers.Activation('relu'))
nn.add(tf.keras.layers.Dropout(0.3))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=50))
nn.add(tf.keras.layers.BatchNormalization())
nn.add(tf.keras.layers.Activation('relu'))
nn.add(tf.keras.layers.Dropout(0.2))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=30))
nn.add(tf.keras.layers.BatchNormalization())
nn.add(tf.keras.layers.Activation('relu'))
nn.add(tf.keras.layers.Dropout(0.2))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 150)               5700

 batch_normalization (BatchN  (None, 150)              600
 ormalization)

 activation (Activation)     (None, 150)               0

 dropout (Dropout)           (None, 150)               0

 dense_1 (Dense)             (None, 75)                11325

 batch_normalization_1 (Batc  (None, 75)               300
 hNormalization)

 activation_1 (Activation)   (None, 75)                0

 dropout_1 (Dropout)         (None, 75)                0

 dense_2 (Dense)             (None, 50)                3800

 batch_normalization_2 (Batc  (None, 50)               200
 hNormalization)

 activation_2 (Activation)   (None, 50)                0

 dropout_2 (Dropout)         (None, 50)                0

 dense_3 (Dense)             (None, 30)                1530

 batch_normalization_3 (Batc  (None, 30)               120
 hNormalization)

 activation_3 (Activation)   (None, 30)                0

 dropout_3 (Dropout)         (None, 30)                0

 dense_4 (Dense)             (None, 1)                 31

=================================================================
Total params: 23,606
Trainable params: 22,996
Non-trainable params: 610
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), metrics=['accuracy'])

In [14]:
# Train the model
nn.fit(X_train_scaled, y_train, epochs=150, batch_size=64, validation_data=(X_test_scaled, y_test), verbose=2)

Epoch 1/150
402/402 - 2s - loss: 0.6009 - accuracy: 0.6998 - val_loss: 0.5785 - val_accuracy: 0.7174 - 2s/epoch - 5ms/step
Epoch 2/150
402/402 - 1s - loss: 0.5817 - accuracy: 0.7173 - val_loss: 0.5753 - val_accuracy: 0.7172 - 1s/epoch - 3ms/step
Epoch 3/150
402/402 - 1s - loss: 0.5792 - accuracy: 0.7181 - val_loss: 0.5711 - val_accuracy: 0.7170 - 1s/epoch - 3ms/step
Epoch 4/150
402/402 - 1s - loss: 0.5774 - accuracy: 0.7195 - val_loss: 0.5707 - val_accuracy: 0.7199 - 1s/epoch - 3ms/step
Epoch 5/150
402/402 - 1s - loss: 0.5774 - accuracy: 0.7184 - val_loss: 0.5704 - val_accuracy: 0.7173 - 1s/epoch - 4ms/step
Epoch 6/150
402/402 - 1s - loss: 0.5743 - accuracy: 0.7230 - val_loss: 0.5701 - val_accuracy: 0.7184 - 1s/epoch - 4ms/step
Epoch 7/150
402/402 - 2s - loss: 0.5728 - accuracy: 0.7219 - val_loss: 0.5729 - val_accuracy: 0.7172 - 2s/epoch - 4ms/step
Epoch 8/150
402/402 - 1s - loss: 0.5731 - accuracy: 0.7217 - val_loss: 0.5716 - val_accuracy: 0.7188 - 1s/epoch - 4ms/step
Epoch 9/150
402/402 - 1s - loss: 0.5739 - accuracy: 0.7203 - val_loss: 0.5689 - val_accuracy: 0.7174 - 1s/epoch - 4ms/step
Epoch 10/150
402/402 - 1s - loss: 0.5708 - accuracy: 0.7231 - val_loss: 0.5685 - val_accuracy: 0.7180 - 1s/epoch - 4ms/step
Epoch 11/150
402/402 - 1s - loss: 0.5737 - accuracy: 0.7234 - val_loss: 0.5700 - val_accuracy: 0.7192 - 1s/epoch - 4ms/step
Epoch 12/150
402/402 - 1s - loss: 0.5706 - accuracy: 0.7239 - val_loss: 0.5702 - val_accuracy: 0.7130 - 1s/epoch - 4ms/step
Epoch 13/150
402/402 - 2s - loss: 0.5717 - accuracy: 0.7211 - val_loss: 0.5704 - val_accuracy: 0.7137 - 2s/epoch - 4ms/step
Epoch 14/150
402/402 - 2s - loss: 0.5707 - accuracy: 0.7234 - val_loss: 0.5687 - val_accuracy: 0.7190 - 2s/epoch - 5ms/step
Epoch 15/150
402/402 - 2s - loss: 0.5698 - accuracy: 0.7235 - val_loss: 0.5679 - val_accuracy: 0.7206 - 2s/epoch - 5ms/step
Epoch 16/150
402/402 - 2s - loss: 0.5701 - accuracy: 0.7249 - val_loss: 0.5675 - val_accuracy: 0.7194 - 2s/epoch - 5ms/step
Epoch 17/150
402/402 - 2s - loss: 0.5693 - accuracy: 0.7240 - val_loss: 0.5680 - val_accuracy: 0.7193 - 2s/epoch - 5ms/step
Epoch 18/150
402/402 - 2s - loss: 0.5680 - accuracy: 0.7225 - val_loss: 0.5720 - val_accuracy: 0.7145 - 2s/epoch - 5ms/step
Epoch 19/150
402/402 - 2s - loss: 0.5697 - accuracy: 0.7236 - val_loss: 0.5735 - val_accuracy: 0.7172 - 2s/epoch - 5ms/step
Epoch 20/150
402/402 - 2s - loss: 0.5704 - accuracy: 0.7245 - val_loss: 0.5789 - val_accuracy: 0.7164 - 2s/epoch - 5ms/step
Epoch 21/150
402/402 - 2s - loss: 0.5684 - accuracy: 0.7250 - val_loss: 0.5682 - val_accuracy: 0.7186 - 2s/epoch - 5ms/step
Epoch 22/150
402/402 - 2s - loss: 0.5686 - accuracy: 0.7252 - val_loss: 0.5698 - val_accuracy: 0.7172 - 2s/epoch - 5ms/step
Epoch 23/150
402/402 - 2s - loss: 0.5695 - accuracy: 0.7245 - val_loss: 0.5740 - val_accuracy: 0.7200 - 2s/epoch - 5ms/step
Epoch 24/150
402/402 - 2s - loss: 0.5687 - accuracy: 0.7251 - val_loss: 0.5681 - val_accuracy: 0.7165 - 2s/epoch - 5ms/step
Epoch 25/150
402/402 - 2s - loss: 0.5687 - accuracy: 0.7257 - val_loss: 0.5686 - val_accuracy: 0.7206 - 2s/epoch - 5ms/step
Epoch 26/150
402/402 - 2s - loss: 0.5691 - accuracy: 0.7257 - val_loss: 0.5814 - val_accuracy: 0.7172 - 2s/epoch - 5ms/step
Epoch 27/150
402/402 - 2s - loss: 0.5675 - accuracy: 0.7255 - val_loss: 0.5702 - val_accuracy: 0.7194 - 2s/epoch - 5ms/step
Epoch 28/150
402/402 - 2s - loss: 0.5661 - accuracy: 0.7269 - val_loss: 0.5706 - val_accuracy: 0.7166 - 2s/epoch - 5ms/step
Epoch 29/150
402/402 - 2s - loss: 0.5675 - accuracy: 0.7262 - val_loss: 0.5682 - val_accuracy: 0.7181 - 2s/epoch - 5ms/step
Epoch 30/150
402/402 - 2s - loss: 0.5673 - accuracy: 0.7252 - val_loss: 0.5701 - val_accuracy: 0.7192 - 2s/epoch - 5ms/step
Epoch 31/150
402/402 - 2s - loss: 0.5666 - accuracy: 0.7266 - val_loss: 0.5680 - val_accuracy: 0.7194 - 2s/epoch - 5ms/step
Epoch 32/150
402/402 - 2s - loss: 0.5671 - accuracy: 0.7240 - val_loss: 0.5680 - val_accuracy: 0.7173 - 2s/epoch - 5ms/step
Epoch 33/150
402/402 - 2s - loss: 0.5659 - accuracy: 0.7268 - val_loss: 0.5664 - val_accuracy: 0.7194 - 2s/epoch - 5ms/step
Epoch 34/150
402/402 - 2s - loss: 0.5672 - accuracy: 0.7253 - val_loss: 0.5669 - val_accuracy: 0.7201 - 2s/epoch - 5ms/step
Epoch 35/150
402/402 - 2s - loss: 0.5667 - accuracy: 0.7261 - val_loss: 0.5686 - val_accuracy: 0.7193 - 2s/epoch - 5ms/step
Epoch 36/150
402/402 - 2s - loss: 0.5669 - accuracy: 0.7253 - val_loss: 0.5679 - val_accuracy: 0.7186 - 2s/epoch - 5ms/step
Epoch 37/150
402/402 - 2s - loss: 0.5656 - accuracy: 0.7265 - val_loss: 0.5671 - val_accuracy: 0.7184 - 2s/epoch - 5ms/step
Epoch 38/150
402/402 - 2s - loss: 0.5670 - accuracy: 0.7264 - val_loss: 0.5676 - val_accuracy: 0.7188 - 2s/epoch - 5ms/step
Epoch 39/150
402/402 - 2s - loss: 0.5661 - accuracy: 0.7258 - val_loss: 0.5708 - val_accuracy: 0.7153 - 2s/epoch - 5ms/step
Epoch 40/150
402/402 - 2s - loss: 0.5651 - accuracy: 0.7249 - val_loss: 0.5666 - val_accuracy: 0.7194 - 2s/epoch - 5ms/step
Epoch 41/150
402/402 - 2s - loss: 0.5660 - accuracy: 0.7278 - val_loss: 0.5655 - val_accuracy: 0.7200 - 2s/epoch - 5ms/step
Epoch 42/150
402/402 - 2s - loss: 0.5672 - accuracy: 0.7249 - val_loss: 0.5665 - val_accuracy: 0.7192 - 2s/epoch - 5ms/step
Epoch 43/150
402/402 - 2s - loss: 0.5645 - accuracy: 0.7280 - val_loss: 0.5669 - val_accuracy: 0.7197 - 2s/epoch - 5ms/step
Epoch 44/150
402/402 - 2s - loss: 0.5669 - accuracy: 0.7256 - val_loss: 0.5695 - val_accuracy: 0.7184 - 2s/epoch - 5ms/step
Epoch 45/150
402/402 - 2s - loss: 0.5658 - accuracy: 0.7266 - val_loss: 0.5700 - val_accuracy: 0.7202 - 2s/epoch - 5ms/step
Epoch 46/150
402/402 - 2s - loss: 0.5638 - accuracy: 0.7277 - val_loss: 0.5677 - val_accuracy: 0.7200 - 2s/epoch - 5ms/step
Epoch 47/150
402/402 - 2s - loss: 0.5667 - accuracy: 0.7267 - val_loss: 0.5675 - val_accuracy: 0.7184 - 2s/epoch - 5ms/step
Epoch 48/150
402/402 - 2s - loss: 0.5660 - accuracy: 0.7250 - val_loss: 0.5677 - val_accuracy: 0.7209 - 2s/epoch - 5ms/step
Epoch 49/150
402/402 - 2s - loss: 0.5661 - accuracy: 0.7265 - val_loss: 0.5705 - val_accuracy: 0.7177 - 2s/epoch - 5ms/step
Epoch 50/150
402/402 - 2s - loss: 0.5671 - accuracy: 0.7246 - val_loss: 0.5693 - val_accuracy: 0.7198 - 2s/epoch - 5ms/step
Epoch 51/150
402/402 - 2s - loss: 0.5657 - accuracy: 0.7271 - val_loss: 0.5687 - val_accuracy: 0.7186 - 2s/epoch - 5ms/step
Epoch 52/150
402/402 - 2s - loss: 0.5640 - accuracy: 0.7264 - val_loss: 0.5685 - val_accuracy: 0.7163 - 2s/epoch - 5ms/step
Epoch 53/150
402/402 - 2s - loss: 0.5648 - accuracy: 0.7265 - val_loss: 0.5687 - val_accuracy: 0.7192 - 2s/epoch - 5ms/step
Epoch 54/150
402/402 - 2s - loss: 0.5668 - accuracy: 0.7251 - val_loss: 0.5675 - val_accuracy: 0.7195 - 2s/epoch - 5ms/step
Epoch 55/150
402/402 - 2s - loss: 0.5638 - accuracy: 0.7265 - val_loss: 0.5689 - val_accuracy: 0.7199 - 2s/epoch - 5ms/step
Epoch 56/150
402/402 - 2s - loss: 0.5654 - accuracy: 0.7280 - val_loss: 0.5711 - val_accuracy: 0.7162 - 2s/epoch - 5ms/step
Epoch 57/150
402/402 - 2s - loss: 0.5643 - accuracy: 0.7260 - val_loss: 0.5742 - val_accuracy: 0.7205 - 2s/epoch - 5ms/step
Epoch 58/150
402/402 - 2s - loss: 0.5619 - accuracy: 0.7287 - val_loss: 0.5668 - val_accuracy: 0.7192 - 2s/epoch - 5ms/step
Epoch 59/150
402/402 - 2s - loss: 0.5652 - accuracy: 0.7278 - val_loss: 0.5675 - val_accuracy: 0.7180 - 2s/epoch - 5ms/step
Epoch 60/150
402/402 - 2s - loss: 0.5639 - accuracy: 0.7272 - val_loss: 0.5703 - val_accuracy: 0.7199 - 2s/epoch - 5ms/step
Epoch 61/150
402/402 - 2s - loss: 0.5632 - accuracy: 0.7265 - val_loss: 0.5705 - val_accuracy: 0.7145 - 2s/epoch - 5ms/step
Epoch 62/150
402/402 - 2s - loss: 0.5651 - accuracy: 0.7266 - val_loss: 0.5663 - val_accuracy: 0.7188 - 2s/epoch - 5ms/step
Epoch 63/150
402/402 - 2s - loss: 0.5647 - accuracy: 0.7271 - val_loss: 0.5701 - val_accuracy: 0.7190 - 2s/epoch - 4ms/step
Epoch 64/150
402/402 - 2s - loss: 0.5641 - accuracy: 0.7262 - val_loss: 0.5662 - val_accuracy: 0.7187 - 2s/epoch - 4ms/step
Epoch 65/150
402/402 - 2s - loss: 0.5627 - accuracy: 0.7274 - val_loss: 0.5663 - val_accuracy: 0.7197 - 2s/epoch - 4ms/step
Epoch 66/150
402/402 - 2s - loss: 0.5630 - accuracy: 0.7281 - val_loss: 0.5665 - val_accuracy: 0.7191 - 2s/epoch - 4ms/step
Epoch 67/150
402/402 - 2s - loss: 0.5651 - accuracy: 0.7272 - val_loss: 0.5716 - val_accuracy: 0.7187 - 2s/epoch - 4ms/step
Epoch 68/150
402/402 - 2s - loss: 0.5640 - accuracy: 0.7273 - val_loss: 0.5674 - val_accuracy: 0.7190 - 2s/epoch - 4ms/step
Epoch 69/150
402/402 - 2s - loss: 0.5659 - accuracy: 0.7270 - val_loss: 0.5674 - val_accuracy: 0.7200 - 2s/epoch - 4ms/step
Epoch 70/150
402/402 - 2s - loss: 0.5647 - accuracy: 0.7281 - val_loss: 0.5668 - val_accuracy: 0.7186 - 2s/epoch - 4ms/step
Epoch 71/150
402/402 - 2s - loss: 0.5642 - accuracy: 0.7270 - val_loss: 0.5664 - val_accuracy: 0.7193 - 2s/epoch - 4ms/step
Epoch 72/150
402/402 - 2s - loss: 0.5638 - accuracy: 0.7261 - val_loss: 0.5682 - val_accuracy: 0.7208 - 2s/epoch - 5ms/step
Epoch 73/150
402/402 - 2s - loss: 0.5636 - accuracy: 0.7271 - val_loss: 0.5668 - val_accuracy: 0.7205 - 2s/epoch - 5ms/step
Epoch 74/150
402/402 - 2s - loss: 0.5638 - accuracy: 0.7271 - val_loss: 0.5724 - val_accuracy: 0.7181 - 2s/epoch - 5ms/step
Epoch 75/150
402/402 - 2s - loss: 0.5633 - accuracy: 0.7271 - val_loss: 0.5685 - val_accuracy: 0.7202 - 2s/epoch - 4ms/step
Epoch 76/150
402/402 - 2s - loss: 0.5652 - accuracy: 0.7267 - val_loss: 0.5694 - val_accuracy: 0.7185 - 2s/epoch - 4ms/step
Epoch 77/150
402/402 - 2s - loss: 0.5637 - accuracy: 0.7274 - val_loss: 0.5675 - val_accuracy: 0.7190 - 2s/epoch - 4ms/step
Epoch 78/150
402/402 - 2s - loss: 0.5643 - accuracy: 0.7271 - val_loss: 0.5664 - val_accuracy: 0.7199 - 2s/epoch - 4ms/step
Epoch 79/150
402/402 - 2s - loss: 0.5635 - accuracy: 0.7269 - val_loss: 0.5687 - val_accuracy: 0.7183 - 2s/epoch - 4ms/step
Epoch 80/150
402/402 - 2s - loss: 0.5651 - accuracy: 0.7278 - val_loss: 0.5677 - val_accuracy: 0.7197 - 2s/epoch - 5ms/step
Epoch 81/150
402/402 - 2s - loss: 0.5634 - accuracy: 0.7286 - val_loss: 0.5669 - val_accuracy: 0.7187 - 2s/epoch - 5ms/step
Epoch 82/150
402/402 - 2s - loss: 0.5623 - accuracy: 0.7280 - val_loss: 0.5669 - val_accuracy: 0.7178 - 2s/epoch - 4ms/step
Epoch 83/150
402/402 - 2s - loss: 0.5639 - accuracy: 0.7277 - val_loss: 0.5702 - val_accuracy: 0.7194 - 2s/epoch - 5ms/step
Epoch 84/150
402/402 - 2s - loss: 0.5618 - accuracy: 0.7281 - val_loss: 0.5680 - val_accuracy: 0.7185 - 2s/epoch - 5ms/step
Epoch 85/150
402/402 - 2s - loss: 0.5632 - accuracy: 0.7276 - val_loss: 0.5662 - val_accuracy: 0.7186 - 2s/epoch - 5ms/step
Epoch 86/150
402/402 - 2s - loss: 0.5636 - accuracy: 0.7262 - val_loss: 0.5674 - val_accuracy: 0.7192 - 2s/epoch - 4ms/step
Epoch 87/150
402/402 - 2s - loss: 0.5622 - accuracy: 0.7285 - val_loss: 0.5665 - val_accuracy: 0.7197 - 2s/epoch - 4ms/step
Epoch 88/150
402/402 - 2s - loss: 0.5617 - accuracy: 0.7278 - val_loss: 0.5672 - val_accuracy: 0.7199 - 2s/epoch - 4ms/step
Epoch 89/150
402/402 - 2s - loss: 0.5630 - accuracy: 0.7282 - val_loss: 0.5674 - val_accuracy: 0.7195 - 2s/epoch - 4ms/step
Epoch 90/150
402/402 - 2s - loss: 0.5621 - accuracy: 0.7286 - val_loss: 0.5664 - val_accuracy: 0.7201 - 2s/epoch - 4ms/step
Epoch 91/150
402/402 - 2s - loss: 0.5626 - accuracy: 0.7281 - val_loss: 0.5674 - val_accuracy: 0.7206 - 2s/epoch - 4ms/step
Epoch 92/150
402/402 - 1s - loss: 0.5647 - accuracy: 0.7282 - val_loss: 0.5658 - val_accuracy: 0.7200 - 1s/epoch - 4ms/step
Epoch 93/150
402/402 - 1s - loss: 0.5630 - accuracy: 0.7295 - val_loss: 0.5686 - val_accuracy: 0.7193 - 1s/epoch - 4ms/step
Epoch 94/150
402/402 - 2s - loss: 0.5626 - accuracy: 0.7282 - val_loss: 0.5669 - val_accuracy: 0.7200 - 2s/epoch - 4ms/step
Epoch 95/150
402/402 - 2s - loss: 0.5622 - accuracy: 0.7268 - val_loss: 0.5666 - val_accuracy: 0.7171 - 2s/epoch - 4ms/step
Epoch 96/150
402/402 - 2s - loss: 0.5617 - accuracy: 0.7289 - val_loss: 0.5669 - val_accuracy: 0.7188 - 2s/epoch - 4ms/step
Epoch 97/150
402/402 - 2s - loss: 0.5623 - accuracy: 0.7283 - val_loss: 0.5678 - val_accuracy: 0.7205 - 2s/epoch - 4ms/step
Epoch 98/150
402/402 - 2s - loss: 0.5609 - accuracy: 0.7282 - val_loss: 0.5698 - val_accuracy: 0.7208 - 2s/epoch - 4ms/step
Epoch 99/150
402/402 - 2s - loss: 0.5631 - accuracy: 0.7266 - val_loss: 0.5698 - val_accuracy: 0.7192 - 2s/epoch - 4ms/step
Epoch 100/150
402/402 - 2s - loss: 0.5625 - accuracy: 0.7280 - val_loss: 0.5684 - val_accuracy: 0.7176 - 2s/epoch - 4ms/step
Epoch 101/150
402/402 - 2s - loss: 0.5618 - accuracy: 0.7275 - val_loss: 0.5665 - val_accuracy: 0.7208 - 2s/epoch - 4ms/step
Epoch 102/150
402/402 - 2s - loss: 0.5648 - accuracy: 0.7275 - val_loss: 0.5668 - val_accuracy: 0.7174 - 2s/epoch - 4ms/step
Epoch 103/150
402/402 - 2s - loss: 0.5622 - accuracy: 0.7287 - val_loss: 0.5676 - val_accuracy: 0.7183 - 2s/epoch - 4ms/step
Epoch 104/150
402/402 - 2s - loss: 0.5618 - accuracy: 0.7292 - val_loss: 0.5700 - val_accuracy: 0.7163 - 2s/epoch - 4ms/step
Epoch 105/150
402/402 - 2s - loss: 0.5636 - accuracy: 0.7265 - val_loss: 0.5663 - val_accuracy: 0.7202 - 2s/epoch - 4ms/step
Epoch 106/150
402/402 - 2s - loss: 0.5624 - accuracy: 0.7286 - val_loss: 0.5671 - val_accuracy: 0.7181 - 2s/epoch - 4ms/step
Epoch 107/150
402/402 - 2s - loss: 0.5629 - accuracy: 0.7274 - val_loss: 0.5665 - val_accuracy: 0.7203 - 2s/epoch - 5ms/step
Epoch 108/150
402/402 - 2s - loss: 0.5626 - accuracy: 0.7302 - val_loss: 0.5688 - val_accuracy: 0.7167 - 2s/epoch - 5ms/step
Epoch 109/150
402/402 - 2s - loss: 0.5634 - accuracy: 0.7291 - val_loss: 0.5674 - val_accuracy: 0.7193 - 2s/epoch - 5ms/step
Epoch 110/150
402/402 - 2s - loss: 0.5614 - accuracy: 0.7274 - val_loss: 0.5672 - val_accuracy: 0.7194 - 2s/epoch - 5ms/step
Epoch 111/150
402/402 - 2s - loss: 0.5630 - accuracy: 0.7297 - val_loss: 0.5675 - val_accuracy: 0.7191 - 2s/epoch - 5ms/step
Epoch 112/150
402/402 - 2s - loss: 0.5619 - accuracy: 0.7276 - val_loss: 0.5661 - val_accuracy: 0.7201 - 2s/epoch - 5ms/step
Epoch 113/150
402/402 - 2s - loss: 0.5628 - accuracy: 0.7294 - val_loss: 0.5682 - val_accuracy: 0.7199 - 2s/epoch - 5ms/step
Epoch 114/150
402/402 - 2s - loss: 0.5626 - accuracy: 0.7270 - val_loss: 0.5703 - val_accuracy: 0.7159 - 2s/epoch - 5ms/step
Epoch 115/150
402/402 - 2s - loss: 0.5624 - accuracy: 0.7278 - val_loss: 0.5671 - val_accuracy: 0.7206 - 2s/epoch - 5ms/step
Epoch 116/150
402/402 - 2s - loss: 0.5616 - accuracy: 0.7292 - val_loss: 0.5697 - val_accuracy: 0.7198 - 2s/epoch - 5ms/step
Epoch 117/150
402/402 - 2s - loss: 0.5615 - accuracy: 0.7287 - val_loss: 0.5663 - val_accuracy: 0.7203 - 2s/epoch - 4ms/step
Epoch 118/150
402/402 - 2s - loss: 0.5627 - accuracy: 0.7275 - val_loss: 0.5661 - val_accuracy: 0.7212 - 2s/epoch - 4ms/step
Epoch 119/150
402/402 - 2s - loss: 0.5629 - accuracy: 0.7282 - val_loss: 0.5714 - val_accuracy: 0.7174 - 2s/epoch - 4ms/step
Epoch 120/150
402/402 - 2s - loss: 0.5622 - accuracy: 0.7287 - val_loss: 0.5666 - val_accuracy: 0.7199 - 2s/epoch - 5ms/step
Epoch 121/150
402/402 - 2s - loss: 0.5628 - accuracy: 0.7275 - val_loss: 0.5661 - val_accuracy: 0.7214 - 2s/epoch - 5ms/step
Epoch 122/150
402/402 - 2s - loss: 0.5627 - accuracy: 0.7281 - val_loss: 0.5680 - val_accuracy: 0.7184 - 2s/epoch - 5ms/step
Epoch 123/150
402/402 - 2s - loss: 0.5624 - accuracy: 0.7281 - val_loss: 0.5666 - val_accuracy: 0.7194 - 2s/epoch - 5ms/step
Epoch 124/150
402/402 - 2s - loss: 0.5611 - accuracy: 0.7292 - val_loss: 0.5680 - val_accuracy: 0.7208 - 2s/epoch - 5ms/step
Epoch 125/150
402/402 - 2s - loss: 0.5620 - accuracy: 0.7278 - val_loss: 0.5691 - val_accuracy: 0.7192 - 2s/epoch - 5ms/step
Epoch 126/150
402/402 - 2s - loss: 0.5616 - accuracy: 0.7290 - val_loss: 0.5675 - val_accuracy: 0.7195 - 2s/epoch - 5ms/step
Epoch 127/150
402/402 - 2s - loss: 0.5617 - accuracy: 0.7270 - val_loss: 0.5677 - val_accuracy: 0.7206 - 2s/epoch - 5ms/step
Epoch 128/150
402/402 - 2s - loss: 0.5626 - accuracy: 0.7287 - val_loss: 0.5662 - val_accuracy: 0.7186 - 2s/epoch - 5ms/step
Epoch 129/150
402/402 - 2s - loss: 0.5613 - accuracy: 0.7290 - val_loss: 0.5690 - val_accuracy: 0.7192 - 2s/epoch - 5ms/step
Epoch 130/150
402/402 - 2s - loss: 0.5636 - accuracy: 0.7266 - val_loss: 0.5687 - val_accuracy: 0.7203 - 2s/epoch - 4ms/step
Epoch 131/150
402/402 - 2s - loss: 0.5619 - accuracy: 0.7287 - val_loss: 0.5678 - val_accuracy: 0.7205 - 2s/epoch - 4ms/step
Epoch 132/150
402/402 - 2s - loss: 0.5632 - accuracy: 0.7282 - val_loss: 0.5660 - val_accuracy: 0.7199 - 2s/epoch - 5ms/step
Epoch 133/150
402/402 - 2s - loss: 0.5619 - accuracy: 0.7298 - val_loss: 0.5699 - val_accuracy: 0.7199 - 2s/epoch - 5ms/step
Epoch 134/150
402/402 - 2s - loss: 0.5613 - accuracy: 0.7303 - val_loss: 0.5670 - val_accuracy: 0.7205 - 2s/epoch - 5ms/step
Epoch 135/150
402/402 - 2s - loss: 0.5624 - accuracy: 0.7290 - val_loss: 0.5677 - val_accuracy: 0.7193 - 2s/epoch - 5ms/step
Epoch 136/150
402/402 - 2s - loss: 0.5611 - accuracy: 0.7290 - val_loss: 0.5659 - val_accuracy: 0.7210 - 2s/epoch - 5ms/step
Epoch 137/150
402/402 - 2s - loss: 0.5609 - accuracy: 0.7292 - val_loss: 0.5706 - val_accuracy: 0.7198 - 2s/epoch - 5ms/step
Epoch 138/150
402/402 - 2s - loss: 0.5626 - accuracy: 0.7285 - val_loss: 0.5667 - val_accuracy: 0.7201 - 2s/epoch - 5ms/step
Epoch 139/150
402/402 - 2s - loss: 0.5605 - accuracy: 0.7296 - val_loss: 0.5688 - val_accuracy: 0.7210 - 2s/epoch - 5ms/step
Epoch 140/150
402/402 - 2s - loss: 0.5603 - accuracy: 0.7294 - val_loss: 0.5696 - val_accuracy: 0.7210 - 2s/epoch - 5ms/step
Epoch 141/150
402/402 - 2s - loss: 0.5624 - accuracy: 0.7296 - val_loss: 0.5684 - val_accuracy: 0.7192 - 2s/epoch - 5ms/step
Epoch 142/150
402/402 - 2s - loss: 0.5599 - accuracy: 0.7275 - val_loss: 0.5654 - val_accuracy: 0.7214 - 2s/epoch - 5ms/step
Epoch 143/150
402/402 - 2s - loss: 0.5621 - accuracy: 0.7278 - val_loss: 0.5707 - val_accuracy: 0.7202 - 2s/epoch - 5ms/step
Epoch 144/150
402/402 - 2s - loss: 0.5614 - accuracy: 0.7270 - val_loss: 0.5678 - val_accuracy: 0.7185 - 2s/epoch - 5ms/step
Epoch 145/150
402/402 - 2s - loss: 0.5632 - accuracy: 0.7276 - val_loss: 0.5676 - val_accuracy: 0.7205 - 2s/epoch - 5ms/step
Epoch 146/150
402/402 - 2s - loss: 0.5616 - accuracy: 0.7283 - val_loss: 0.5718 - val_accuracy: 0.7166 - 2s/epoch - 5ms/step
Epoch 147/150
402/402 - 2s - loss: 0.5631 - accuracy: 0.7298 - val_loss: 0.5671 - val_accuracy: 0.7209 - 2s/epoch - 5ms/step
Epoch 148/150
402/402 - 2s - loss: 0.5613 - accuracy: 0.7281 - val_loss: 0.5655 - val_accuracy: 0.7183 - 2s/epoch - 5ms/step
Epoch 149/150
402/402 - 2s - loss: 0.5610 - accuracy: 0.7292 - val_loss: 0.5658 - val_accuracy: 0.7213 - 2s/epoch - 5ms/step
Epoch 150/150
402/402 - 2s - loss: 0.5621 - accuracy: 0.7293 - val_loss: 0.5672 - val_accuracy: 0.7205 - 2s/epoch - 5ms/step

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5672 - accuracy: 0.7205 - 504ms/epoch - 2ms/step
Loss: 0.5672211050987244, Accuracy: 0.7204664945602417

In [16]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")